@startuml

class Cuadro{
Título: 0..* Texto
Cronología: 1 Tiempo
Técnica: 1 enum Técnica
Sub-técnica: 1 enum Sub-Técnica
Material del soporte: 1 enum Material
Autor: 1 Texto
Estado de conservación: 1 enum Estado de Conservación
}

class Lugar{
Institución: 1 Texto
Ciudad: 1 Texto
País: 1 Texto
}

Cuadro = Lugar :0..*  Se localiza en >  1 "Ubicacion"

class Replica{
Título: 0..* Texto
Cronología: 1 Tiempo
Técnica: 1 enum Técnica
Sub-técnica: 1 enum Sub-Técnica
Material del soporte: 1 enum Material
Autor: 1 Texto
Estado de conservación: 1 enum Estado de Conservación
}

Replica = Cuadro : "copia" Es replica de > "original"

@enduml